---
- hosts: dhcp*
  become: true
  # pre_tasks:
  #   - name: set IPv6 address of host system
  #     local_action: command 'ip address add fdad:d155:f869:55b4::1/64 dev enp0s8'
  #   - name: set IPv6 address of DHCP server
  #     command: 'ip address add fdad:d155:f869:55b4::2/64 dev enp0s8'
  vars:
    dhcp_global_default_lease_time: 28800   # 8hrs
    dhcp_global_max_lease_time: 43200       # 12 hrs
    dhcp_global_subnet_mask: 255.255.255.0
    dhcp_global_broadcast_address: 192.168.76.255
    # dhcp_global_routers: 10.0.2.2
    dhcp_global_domain_name: example.com
    dhcp_global_domain_name_servers:
      - 8.8.8.8
      - 8.8.4.4
#    dhcp_global_bootp: allow
#    dhcp_global_booting: allow
#    dhcp_global_next_server: 192.168.222.3
#    dhcp_global_filename: boot.img

#    dhcp_global_classes:
#      - name: vbox
#        match: 'match if binary-to-ascii(16,8,":",substring(hardware, 1, 3)) = "8:0:27"'

    dhcp_subnets:
      - ip: 192.168.76.0
        netmask: 255.255.255.0
        domain_name_servers:
          - 1.1.1.1
          - 8.8.8.8
        range_begin: 192.168.76.50
        range_end: 192.168.76.100
#        pools:
#          - default_lease_time: 1800
#            max_lease_time: 3600
#            range_begin: 192.168.76.101
#            range_end: 192.168.76.127
#             allow: 'members of "vbox"'
#      - ip: 192.168.76.128
#        default_lease_time: 3600
#        max_lease_time: 7200
#        netmask: 255.255.255.128
#        domain_name_servers: 1.1.1.1
#        routers: 192.168.76.129

  roles:
    - dhcp
